package runner;

import org.junit.platform.engine.discovery.DiscoverySelectors;
import org.junit.platform.launcher.Launcher;
import org.junit.platform.launcher.LauncherDiscoveryRequest;
import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;
import org.junit.platform.launcher.core.LauncherFactory;
import org.junit.platform.launcher.listeners.SummaryGeneratingListener;
import org.junit.platform.launcher.listeners.TestExecutionSummary;

import java.io.*;
import java.nio.file.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * FailedTestsRunner
 *
 * Reads the failed-tests.txt file generated by TestListener after a test run,
 * re-executes only the failed test methods, and writes a retry report.
 *
 * Usage (Maven):
 *   mvn exec:java -Dexec.mainClass="runner.FailedTestsRunner"
 *
 * Or trigger from CI after a failed run:
 *   java -cp target/... runner.FailedTestsRunner
 *
 * Failed tests file format (one per line):
 *   com.example.api.GetSessionTest#shouldAuthenticateUser
 */
public class FailedTestsRunner {

    private static final String FAILED_TESTS_FILE = "target/failed-tests.txt";
    private static final String RETRY_REPORT_FILE = "target/retry-report.txt";
    private static final int MAX_RETRIES = 2;

    public static void main(String[] args) throws Exception {
        System.out.println("═══════════════════════════════════════════════");
        System.out.println("       FAILED TESTS RETRY RUNNER");
        System.out.println("═══════════════════════════════════════════════");

        List<String> failedTests = loadFailedTests();

        if (failedTests.isEmpty()) {
            System.out.println("No failed tests found. Nothing to retry.");
            return;
        }

        System.out.printf(" Found %d failed test(s). Starting retry (max %d attempts)...%n%n",
                failedTests.size(), MAX_RETRIES);

        List<String> stillFailing = new ArrayList<>();
        List<String> recovered = new ArrayList<>();

        for (String testId : failedTests) {
            boolean passed = retryTest(testId);
            if (passed) {
                recovered.add(testId);
            } else {
                stillFailing.add(testId);
            }
        }

        writeRetryReport(failedTests, recovered, stillFailing);
        printSummary(recovered, stillFailing);

        // Exit with non-zero code if tests still fail (so CI can catch it)
        if (!stillFailing.isEmpty()) {
            System.exit(1);
        }
    }

    /**
     * Reads failed test IDs from the file written by TestListener.
     */
    private static List<String> loadFailedTests() throws IOException {
        Path path = Paths.get(FAILED_TESTS_FILE);
        if (!Files.exists(path)) {
            System.out.println(" No failed-tests.txt found at: " + FAILED_TESTS_FILE);
            return new ArrayList<>();
        }

        List<String> tests = new ArrayList<>();
        for (String line : Files.readAllLines(path)) {
            String trimmed = line.trim();
            if (!trimmed.isEmpty() && !trimmed.startsWith("#")) {
                tests.add(trimmed);
            }
        }
        return tests;
    }

    /**
     * Retries a single test up to MAX_RETRIES times.
     * Returns true if it eventually passes.
     */
    private static boolean retryTest(String testId) {
        String[] parts = testId.split("#");
        if (parts.length != 2) {
            System.out.printf(" Skipping invalid test ID format: %s%n", testId);
            return false;
        }

        String className = parts[0];
        String methodName = parts[1];

        for (int attempt = 1; attempt <= MAX_RETRIES; attempt++) {
            System.out.printf("  ▶ Attempt %d/%d: %s#%s%n", attempt, MAX_RETRIES, className, methodName);

            try {
                Class<?> testClass = Class.forName(className);

                LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                        .selectors(DiscoverySelectors.selectMethod(testClass, methodName))
                        .build();

                SummaryGeneratingListener listener = new SummaryGeneratingListener();
                Launcher launcher = LauncherFactory.create();
                launcher.discover(request);
                launcher.execute(request, listener);

                TestExecutionSummary summary = listener.getSummary();

                if (summary.getTestsFailedCount() == 0 && summary.getTestsSucceededCount() > 0) {
                    System.out.printf("    PASSED on attempt %d%n", attempt);
                    return true;
                } else {
                    System.out.printf("     Still failing (attempt %d)%n", attempt);
                    summary.getFailures().forEach(f ->
                            System.out.printf("       Cause: %s%n", f.getException().getMessage()));
                }

            } catch (ClassNotFoundException e) {
                System.out.printf("     Class not found: %s%n", className);
                return false;
            }

            // Brief pause between retries
            if (attempt < MAX_RETRIES) {
                try { Thread.sleep(2000); } catch (InterruptedException ignored) {}
            }
        }

        System.out.printf("    💀 FAILED after %d attempts%n", MAX_RETRIES);
        return false;
    }

    /**
     * Writes a human-readable retry report to target/retry-report.txt
     */
    private static void writeRetryReport(List<String> all, List<String> recovered, List<String> stillFailing)
            throws IOException {
        Files.createDirectories(Paths.get("target"));
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        try (PrintWriter writer = new PrintWriter(new FileWriter(RETRY_REPORT_FILE))) {
            writer.println("═══════════════════════════════════════════════");
            writer.println("         FAILED TESTS RETRY REPORT");
            writer.println("═══════════════════════════════════════════════");
            writer.println("Generated: " + timestamp);
            writer.println("Total retried : " + all.size());
            writer.println("Recovered     : " + recovered.size());
            writer.println("Still failing : " + stillFailing.size());
            writer.println();

            if (!recovered.isEmpty()) {
                writer.println("✅ RECOVERED (Flaky - passed on retry):");
                recovered.forEach(t -> writer.println("   - " + t));
                writer.println();
            }

            if (!stillFailing.isEmpty()) {
                writer.println("STILL FAILING (Genuine failures):");
                stillFailing.forEach(t -> writer.println("   - " + t));
                writer.println();
            }

            writer.println("═══════════════════════════════════════════════");
        }

        System.out.println("\n📄 Retry report written to: " + RETRY_REPORT_FILE);
    }

    private static void printSummary(List<String> recovered, List<String> stillFailing) {
        System.out.println();
        System.out.println("═══════════════════════════════════════════════");
        System.out.printf("  ✅ Recovered (flaky): %d%n", recovered.size());
        System.out.printf("  Still failing:     %d%n", stillFailing.size());
        System.out.println("═══════════════════════════════════════════════");
    }
}

